#!/bin/bash

echo "=== TODAY'S WORK PLAN: Rodney + Lisa ==="
echo "Date: $(date)"
echo ""

echo "🎯 PRIORITIES:"
echo "1. Rodney Mayo (Lead 24) - Newsletter/Content AI"
echo "2. Lisa Martinez (Lead 67) - Voice AI Receptionist"
echo "3. Ayala Integration Setup (Lead 110)"
echo ""

echo "📋 RODNEY MAYO (Lead 24) - 4 Tasks"
echo "==================================="
echo "Current Tasks:"
./bin/iris sdk:call leads.tasks.all 24 --json 2>&1 | jq -r '.tasks[] | "✅ \(.title)"'

echo ""
echo "ACTION PLAN:"
echo "1. Send comprehensive Entropy AI deliverables package"
echo "   - Time: 30 minutes"
echo "   - Status: READY TO DO"
echo ""
echo "2. Fix CloudFiles SDK authorization and test RAG quality"
echo "   - Time: 30 minutes"
echo "   - Status: TECHNICAL FIX"
echo ""
echo "3. update website w testimonials"
echo "   - Time: 30 minutes"
echo "   - Status: WEBSITE UPDATE"
echo ""
echo "4. send testimonials via file"
echo "   - Time: 15 minutes"
echo "   - Status: EMAIL DELIVERY"
echo ""

echo "📋 LISA MARTINEZ (Lead 67) - 3 Tasks"
echo "===================================="
echo "Current Tasks:"
./bin/iris sdk:call leads.tasks.all 67 --json 2>&1 | jq -r '.tasks[] | "✅ \(.title)"'

echo ""
echo "ACTION PLAN:"
echo "1. Build Voice AI Receptionist for ATX Beauty Lab"
echo "   - Time: 60 minutes"
echo "   - Status: AGENT CREATION"
echo "   - Requires: VAPI integration, salon knowledge"
echo ""
echo "2. Renegotiate monthly terms"
echo "   - Time: 30 minutes"
echo "   - Status: NEGOTIATION"
echo "   - Type: Contract terms adjustment"
echo ""
echo "3. PDF design for consent forms"
echo "   - Time: 30 minutes"
echo "   - Status: DESIGN WORK"
echo "   - Tool: Canva/Figma or similar"
echo ""

echo "📋 AYALA INTEGRATION TASKS (Lead 110)"
echo "====================================="
echo "Current Integration Tasks:"
./bin/iris sdk:call leads.tasks.all 110 --json 2>&1 | jq -r '.tasks[] | select(.title | contains("WordPress") or contains("Notion") or contains("Trello") or contains("Integration")) | "✅ \(.title)"'

echo ""
echo "DETAILED IMPLEMENTATION PLAN:"
echo "1. WordPress Integration Setup"
echo "   - SDK Command: ./bin/iris integrations connect wordpress"
echo "   - Test: ./bin/iris integrations test wordpress"
echo "   - Time: 15 minutes"
echo ""
echo "2. Notion Integration Setup"
echo "   - SDK Command: ./bin/iris integrations connect notion"
echo "   - Test: ./bin/iris integrations test notion"
echo "   - Time: 15 minutes"
echo ""
echo "3. Trello Integration Setup"
echo "   - SDK Command: ./bin/iris integrations connect trello"
echo "   - Test: ./bin/iris integrations test trello"
echo "   - Time: 15 minutes"
echo ""

echo "⏰ TIME BLOCKS:"
echo "=============="
echo "9:00 AM - 10:00 AM: Rodney deliverables package"
echo "10:00 AM - 10:30 AM: Rodney CloudFiles fix"
echo "10:30 AM - 11:00 AM: Rodney testimonials update"
echo "11:00 AM - 11:15 AM: Rodney testimonials email"
echo ""
echo "1:00 PM - 2:00 PM: Lisa Voice AI Receptionist setup"
echo "2:00 PM - 2:30 PM: Lisa terms renegotiation"
echo "2:30 PM - 3:00 PM: Lisa PDF design"
echo ""
echo "3:00 PM - 3:45 PM: Ayala integrations setup"
echo ""

echo "🎯 SUCCESS METRICS:"
echo "=================="
echo "- Rodney: 4/4 tasks completed"
echo "- Lisa: 3/3 tasks completed"
echo "- Ayala: 3/3 integrations connected"
echo "- Total: 10 tasks completed today"
echo "- Completion Rate: From 0% → ~17%"

echo ""
echo "🚀 TOMORROW PREP: Tha Juan (Lead 412)"
echo "====================================="
echo "Tasks to focus on:"
./bin/iris sdk:call leads.tasks.all 412 --json 2>&1 | jq -r '.tasks[] | "• \(.title)"' | head -6

echo ""
echo "Priority tomorrow:"
echo "1. Setup delivery meeting"
echo "2. Demo Call Logs & Agent Control Features"
echo "3. Fix UI bugs in AI Receptionist agent interface"
echo "4. Setup Agent Control & Voice Settings"

